### PR TITLE
Update Format-Json.ps1

### LINKED ISSUE #74: There is a potential bug in the Format-Json function.
`ArgumentOutOfRangeException` will be raised when executing [Format-Json](https://github.com/mkht/pspm/blob/569c7eca5f0862d2a979104b44f3c9923be668ce/functions/Format-Json.ps1) on a JSON with an array value that contains a mixture of literal and hash values.

#### Notes 1.
This issue was reported by @vody. Thank you very much !

#### Notes 2.
This is a potential issue in a private function and does not affect the operation of pspm.

### Example Json:
```js
{
  "key": [
    "Literal Value 1",
    {
      "John": "American",
      "Allen": "Italy",
      "Kojima": "Japanese"
    },
    "Literal Value 2"
  ]
}
```

### Expected behavior
```powershell
$json = Get-Content example.json
$json | Format-Json
{
  "key": [
    "Literal Value 1",
    {
      "John": "American",
      "Allen": "Italy",
      "Kojima": "Japanese"
    },
    "Literal Value 2"
  ]
}
```

### Actual behavior
```powershell
$json = Get-Content example.json
$json | Format-Json
Specified argument was out of the range of valid values.
Parameter name: times
At line:19 char:13
+             $line = (' ' * $indent * 2) + $_.TrimStart().Replace(':   ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], ArgumentOutOfRangeExce 
   ption
    + FullyQualifiedErrorId : System.ArgumentOutOfRangeException
```

#### 1. Reads JSON as a string literal
```powershell
$json = Get-Content example.json -Raw
$json | Format-Json
```

### PR DESCRIPTION
**Pull request by vody**
Update regex expressions solving an issue when [,{,},] characters exists in a value

### CODE REVIEW

**Comment by mkht** [comment]
Hi @vody 
Thank you for your contribution! Please give me a moment so I will review about your code. :-)

**Comment by mkht** [comment]
@vody.
I made an Issue #74 about the problem that this PR will solve. Can you confirm that I am not mistaken in my understanding?

**Comment by vody** [comment]
Hi @mkht 
Actually I was referring to a json with { [ ] } characters in it's value. Like this one: 
`{
	"key1": "val{0}e1",
	"key2": "value2"
}`
With original version, "key2" line will be indented incorrectly. But I am happy that it is solving other issue as well 👍

**Review by mkht — APPROVED** [review]

**Comment by mkht** [comment]
Hi @vody 
Thank you for the explanation. Your code looks great, so I will merge it immediately.

After I do the merge, I'm going to make some additional edits to the code to resolve it, including the issue I presented in #74. 😄

**Pull request merged**
